### PR TITLE
Rename pt.txt to pt_br.txt

### PR DESCRIPTION
**Pull request by afmachado**

### CODE REVIEW

**Comment by VanessaE** [comment]
As @kaeza asked in another similar thread, what's the purpose of renaming this file?

**Comment by Guard13007** [comment]
@VanessaE From a quick Google search: pt -> Portuguese, pt_br -> Portuguese (Brazil)

Now I don't know the difference between the two, my guess would be @afmachado has some knowledge of the difference or which was written into pt.txt and has determined that the language therein is more specific to a Brazilian dialect.

Again, I have no knowledge of this, so I cannot confirm this, but if that is true, the change should potentially be made. It could cause issues for users using `pt` already. (I do not know what the minetest code does if a primary language is not specified but a dialect is specified, perhaps it should be duplicated in case another dialect comes along? but that leads to bloat, and .. I do not possess the knowledge to know the appropriate action here..)

**Comment by sofar** [comment]
this is correct. Portuguese (pt_PT, aka `pt`) is different enough from Brazilian Portuguese (pt_BR) that they're translated separately.

However, given the other pt_BR patch is a bit of a mess, I really want someone to close this and the other one and clean it all up instead. This patch, without even a commit message explaining anything, is not OK (only a portuguese speaking person can check it).

**Comment by afmachado** [comment]
This translation to Brazilian Portuguese is correct. Please modify the file name to: pt_BR.txt or pt_rBR.txt. Thanks.

**Pull request merged**
